
const arr = [{firstname: 'Toriqul'}];

try{
	console.log(arr[0].firstname);

}
catch(e){
	console.log('exception');
}